### ISSUE TITLE
`convertTimezone` function seems to be missing in SOQL

### ISSUE THREAD

**Issue by sam-superframe** [aheber/tree-sitter-sfapex#18]
I was testing out examples from the docs and it seems the SOQL lifted from here generates an `ERROR` node.

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_convert_time_zone.htm

```
SELECT HOUR_IN_DAY(convertTimezone(CreatedDate)), SUM(Amount)
FROM Opportunity
GROUP BY HOUR_IN_DAY(convertTimezone(CreatedDate))
```

From what I can tell, it looks like it's just that `convertTimezone` is missing as a possible function.

<img width="1542" alt="image" src="https://github.com/aheber/tree-sitter-sfapex/assets/144175472/12abb106-b06e-4910-8c0a-97a62fbb4ec6">

**Comment by aheber** [comment]
Thanks! When I wrote it I limited it to certain function names, I'm rethinking that decision. You're right I didn't have that one listed, I'm going to change it a bit so it treats function names as a labeled identifier instead of a limited set of string matches.

This will have a bit of a cascade effect, and including some queries. FYI @finxxi once I get this released, when you increment the git hash for NVIM you'll have some query changes to do in that package.

I'll get final details later but I think going to change the "function_name" node type into "identifier" with a "field" name of "function_name."

**Comment by sam-superframe** [comment]
I think that's a reasonable change. I'm not sure it's the parser's responsibility to ensure that a given function exists or not.

**Comment by aheber** [comment]
Sorry, @xixiaofinland I was tagging the wrong user yesterday. This and the associated PR will cause the need for query updates.

**Comment by xixiaofinland** [comment]
got it sir :) @aheber
