### ISSUE TITLE
[Question] syntax highlight improvement

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#22]
The next thing to improve for me is the variable or method syntax highlight in the local scope. 
Currently it doesn't recognize it's the same as defined in the context above, such as the `controller` in the screenshot below (because the syntax highlight differs)

Is this purely defined in `local.scm` or partly in the parser as well?

![Image 010](https://github.com/aheber/tree-sitter-sfapex/assets/13655323/a6a4a7d8-b3ba-4284-ae21-6f055cfc202b)

**Comment by aheber** [comment]
The parser doesn't understand references inside a file or cross file scopes. It doesn't correlate data, unfortunately.

I think to get this support it would need to be a language server construct, not just a highlights configuration. That needs context about the different scopes but more so the relationships between different identifiers.

If it is possible to get Tree-Sitter to understand those differences in the Queries I don't know how. If nvim-tree-sitter can do it it is because they are performing some of that language server behavior to correlate. This might be in the 'local.scm` queries or similar. If they have this working for another language I'd love to see some examples and we can figure out what they are doing.

An example about this, when I was trying to get `static final` variables highlighted as `constants` I could do it at the definition because I could look at the modifiers to see it was `static final` but when that variable was used further down I couldn't cross-reference the definition. I ended up just assuming things with UPPER_SNAKE_CASE were all constants, even if they weren't actually.


When I'm in VSCode I know that Javascript's language server provides this type of contextual information, changing an identifiers color depending of it was defined with `let` or `const` or even if it is defined but never used. When I looked into it VSCode's docs said that needed to be a function of the Langauge Server.

**Comment by xixiaofinland** [comment]
I will check with nvim treeistter gurus and get back here.
Do you know How SF VSCode plugins handle Apex syntax highlighting? Does it use APIs in jorje.jar? @aheber

**Comment by xixiaofinland** [comment]
Well, after chatting in the nvim-treesitter, the answer is:
Treesitter cannot do cross-file and it has zero semantic information (only the locals.scm tries to do a bit of that, badly).

Maybe I can do a bit of the locals.scm at least....

**Comment by aheber** [comment]
VSCode handles Apex code highlights using a TextMate Language syntax (lots of RegEx) which lives here, https://github.com/forcedotcom/apex-tmLanguage

In a perfect world the VSCode team would move syntax highlighting into the Language Server so it can be way more contextual. 

I've looked at using Tree-Sitter for highlights in VSCode but I think I would have to take over as the Apex Language Server, or at least be a front for it so I can manage/augment some of the queries and pass everything else back to the Apex Lang Server.

I don't think I'm at a point where I could really entertain a project at that level. In my mind we could do a lot better if the Apex Language server was open sourced but there are some complications with that. The code the runs the Language Server is supported directly by Salesforce Platform Code and not all of it could be open sourced. So we either wait for Salesforce to figure out a plan, hope they put more resources into it, or the community builds a ground-up new language server.

**Comment by xixiaofinland** [comment]
Totally understand. I also wished the Official language server could offer many more features so all editing tools benefits in addition to VSCode.

Let's forget about this for now. I will deal with `locals.scm` when I get the chance to.
