### ISSUE TITLE
Why is the src dir under the apex dir?

### ISSUE THREAD

**Issue by jbenge1** [aheber/tree-sitter-sfapex#30]
Looking through other tree-sitters in the [https://github.com/tree-sitter](https://github.com/tree-sitter) repo, most are structured such that the src dir is at the top level. I have created an apex extension for the zed editor but it is expecting the previously mentioned structure. 

Is there a reason behind the dir structure you have chosen or can it be changed to match the others?

**Comment by aheber** [comment]
This has a different structure because there are more than one grammar in this repo.

This is a pattern that is present in a few of the repos under tree-sitter but not many, such as https://github.com/tree-sitter/tree-sitter-typescript

I don't know much about Zed's available configuration but NVIM allows you to add a "location" string if your parser is not in the root of the project.

https://github.com/nvim-treesitter/nvim-treesitter/blob/0f6be799628589c2576194f5735924138f537c2f/lua/nvim-treesitter/parsers.lua#L95

If you can't find a viable option I can take a look at Zed next week and see if they already have configuration for some of the multi-grammar repos. They might already have examples of how to do this. You could also look on their past issues to see if this has come up before.

I don't think restructuring my repo would be a viable option for me but I'll try and think of others.

**Comment by jbenge1** [comment]
I'll close this issue, I was able to find one example extension that uses a tree-sitter with a structure similar to yours (the rest were natively supported and I was unable to find the source code)

**Comment by aheber** [comment]
@jbenge1 glad you were able to find a solution! For posterity, could you share what settings you used and where you found them? Just in case anyone else would like to replicate your results.

Thanks!

**Comment by jbenge1** [comment]
Certainly! Amazingly similar to neovim in the extension.toml you can specify a `path`

```
id = "apex"
name = "Apex"
description = "Apex language support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Justin Benge <justinbng36@gmail.com"]
repository = "https://github.com/jbenge1/zed-apex-extension.git"

[grammars.apex]
repository = "https://github.com/aheber/tree-sitter-sfapex.git"
commit = "c99ad4b16d112fea91745e3f1b769754239fdaba"
path = "apex"
```

**Comment by aheber** [comment]
Thanks, I'll have to find some time to try out Zed and already knowing how to add basic Apex support would be great!
