### ISSUE TITLE
Parsing @isTest() 

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#41]
jorje accepts `@isTest()` and prettier will format it into `@isTest`
I'm not even sure if we want to allow this, just FYI.

```
@isTest
private class A{
    @isTest()
    private static void sortContactsLastFirstName() {
     }
}
```

**Comment by aheber** [comment]
It makes sense why it would be allowed. Really it is just optional. I happen to have never run into it before.

Easy enough to add with the others.

**Comment by xixiaofinland** [comment]
why is it allowed? Because the annotation should have accepted `()`?

**Comment by aheber** [comment]
Yes, I've never seem them added if people didn't put something inside of them. I didn't know, and the parser doesn't accept just the parens but it appears it is a valid construct.

The change is really easy, I just fix it here, https://github.com/aheber/tree-sitter-sfapex/blob/69330ef89fb6b7b2dd16b639d86811e9262c7369/apex/grammar.js#L537

If it were a `repeat` instead of a `repeat1` then it works fine. (update ready and coming soon)

**Comment by aheber** [comment]
This is available now.

**Comment by xixiaofinland** [comment]
This parses correctly, but I'm puzzled, shall I remove the `()` and turn it automatically into @IsTest ?

**Comment by aheber** [comment]
From a formatting perspective, I would assume it is safe to trim the empty parens off but I don't know if that is universally true for all current and future annotations.

I would favor trimming them off but be ready for something to come up where you have to keep it in special cases that are as of yet unknown.
