### ISSUE TITLE
SOSL parsing fails

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#54]
This works in PA

```
class SOSLClass {
  void bindKeyword() {
    List<List<SObject>> searchResult;
    searchResult = [
      FIND 'Hello'
      RETURNING
        Contact(FirstName, LastName USING LOOKUP l BIND i = 'bar', j = 'baz')
    ];
  }
}
```

**Comment by xixiaofinland** [comment]
I have no context, they are from PA's test suit [here](https://github.com/dangmai/prettier-plugin-apex/blob/0e4bd3495e09b35c93d9aa5264a85319311b96c0/packages/prettier-plugin-apex/tests/sosl/SOSL.cls).

I bet Dang collected these rare ones and put them into the suit.

**Comment by xixiaofinland** [comment]
maybe this section in the file gives a bit hint.


```
  void withPricebookId() {
    List<List<SObject>> searchResult;
    searchResult = [FIND 'Hello' WITH PriceBookId = '01sxx0000002MffAAE'];
    // Technically the following line is not correct Apex, since PriceBookId
    // cannot be used with IN, but it's the only semi-accurate example I can
    // find for SearchWithClauseValue with multiple string values
    searchResult = [
      FIND 'Hello'
      WITH PriceBookId IN ('01sxx0000002MffAAE', '1234')
    ];
    searchResult = [
      FIND 'Hello'
      WITH PriceBookId = '01sxx0000002MffAAE'
      WITH PriceBookId = '01sxx0000002MffAAE'
      WITH PriceBookId = '01sxx0000002MffAAE'
    ];
  }

```

**Comment by aheber** [comment]
Thanks, I'll see if I can find anything.

**Comment by aheber** [comment]
Looks like it was introduced in Winter '15, added and pulled from the Release Notes, but the functionality still exists. We simply don't know what the scope of the syntax is and how to parse it correctly. At this point it is probably best that I add support for the few examples we have, leave it fairly broad, and we can fine tune it when bug reports come in.

I think between your examples and these sources I have enough to get a sense for it. 

https://salesforce.stackexchange.com/questions/192280/undocumented-soql-syntax-using-lookup

https://ideas.salesforce.com/s/idea/a0B8W00000GdoFkUAJ/document-finalise-using-lookup-syntax


> SOQL query filtering with the new USING LOOKUP clause
Removed the USING LOOKUP section because the USING LOOKUP feature has been removed from this release.

https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_winter15_release_notes.pdf

**Comment by xixiaofinland** [comment]
totally up to you, I willl follow. I don't even need to get it done now, it's such a small niche.

**Comment by aheber** [comment]
OK, I think I have a summary of how this works, at least what I've been able to test and observe in a real org. I'll add my notes and context here and maybe someone else will find this documentation useful some day. I'm sure there will be some variant that I'm not covering here but we'll handle those when we become aware of them.

`SELECT Id FROM [Object] USING LOOKUP [Object].[Field]` syntax is used to filter down to records that would be eligible to meet the criteria of a Lookup field. That field is referenced using it's schema address, in the above `[Object].[Field]` would be that address.

This syntax can only be used with fields that have Lookup Filter criteria configured. If you try and use a Lookup field that doesn't have Filter Criteria configured you'll see an error similar to `Invalid field: '[Object].[Field]' may not be used in this context`.

Assume we add a custom object to our org. This object's API name is `TestObj__c` and on that object I add two fields that are lookups to Contact and Account respectively:
* `ContactLooupField__c`
* `AccountLookupField__c`

So if I have static Lookup Filter criteria such as a hardcoded Record Type or only allow Contacts with the `Is_Active__c` checkbox checked, this would work great to find matches: `SELECT Id FROM Contact USING LOOKUP TestObj__c.ContactLookupField__c`, it would automatically filter the Contacts according to the Lookup Filter.

It gets a little more complicated when you need to handle dynamic values. If on `ContactLookupField__c` I add Lookup Filter criteria that forces the `Contact.AccountId` to match `TestObj__c.AccountLookupField__c`. So for a given `TestObj__c` record, if I were to try and find eligible Contacts they would have to be linked to the same Account as my record.

If all I do is run `SELECT Id FROM Contact USING LOOKUP TestObj__c.ContactLookupField__c` then it will find me Contacts that have no AccountId value set. This is because our query doesn't have any record context to match against and when it checks to see what the `AccountLookupField__c` value passed to the query is, it will be empty, thus only matching records that also have empty values.

To deal with this we need to pass that context into SOQL so it knows what value our context record has and can then use that to match against eligible Contact records. `USING LOOKUP` appears to offer an optional `BIND` clause of comma-separated `[Field] = [value]` pairs to provide that record context into the Lookup Filter matching logic.

To make our dynamic example work we might build a query like this `SELECT FirstName, LastName FROM Contact USING LOOKUP TestObj__c.ContactLookupField__c BIND AccountLookupField__c = '001Em00000TOP85IAH'` which provides the Account Id value that our record holds in it's `AccountLookupField__c` and can then be used to find matching records.

If we made the Lookup Filter more complicated we might see something like `SELECT FirstName, LastName FROM Contact USING LOOKUP TestObj__c.ContactLookupField__c BIND AccountLookupField__c = '001Em00000TOP85IAH', Field2__c = 'Test Value'` to pass multiple bound field values into the Lookup Filter.

**Comment by aheber** [comment]
> maybe this section in the file gives a bit hint.
> 
> ```
>   void withPricebookId() {
>     List<List<SObject>> searchResult;
>     searchResult = [FIND 'Hello' WITH PriceBookId = '01sxx0000002MffAAE'];
>     // Technically the following line is not correct Apex, since PriceBookId
>     // cannot be used with IN, but it's the only semi-accurate example I can
>     // find for SearchWithClauseValue with multiple string values
>     searchResult = [
>       FIND 'Hello'
>       WITH PriceBookId IN ('01sxx0000002MffAAE', '1234')
>     ];
>     searchResult = [
>       FIND 'Hello'
>       WITH PriceBookId = '01sxx0000002MffAAE'
>       WITH PriceBookId = '01sxx0000002MffAAE'
>       WITH PriceBookId = '01sxx0000002MffAAE'
>     ];
>   }
> ```

I'm going to break this out to another issue. This is a different and unrelated bug.

**Comment by aheber** [comment]
Should be updated now. Will update the NPM package later.

**Comment by xixiaofinland** [comment]
works!
