### ISSUE TITLE
Apex syntax reference?

### ISSUE THREAD

**Issue by mjambon** [aheber/tree-sitter-sfapex#7]
I'm trying to figure out what "Anonymous Apex" means as far as syntax goes (https://github.com/aheber/tree-sitter-sfapex/issues/3) and why the entrypoint of the grammar is currently limited to a sequence of declarations rather than a sequence of statements (`repeat($.declaration)` vs. the more complete `repeat($.statement)` [as found in tree-sitter-java](https://github.com/tree-sitter/tree-sitter-java/blob/09d650def6cdf7f479f4b78f595e9ef5b58ce31e/grammar.js#L79)). What's the best available reference for the Salesforce Apex grammar? What do you use?

**Comment by aheber** [comment]
High level, there are a few forms of "Apex" code.

1. Write an Apex Class file (single outer class, inner classes supported) and upload that to Salesforce
2. Write an Apex Trigger file (single outer trigger, just a series of expressions inside, no classes or methods) and upload
3. Write an Apex Enum file (same file container as a Class but containing an Enum definition instead of a class definition) and upload
4. Anonymous Apex, not saved as rerun-able code. One-time arbitrary run executed via API. Can be saved locally but can't be uploaded to Salesforce aside from per-execution.

We'll generally call the first three "saved apex."

Saved Apex doesn't have support for multiple top-level definitions per file and a stored piece of Apex is not directly executable. It must be executed by something else (database action, API action, Anonymous Apex, etc...)

Anonymous Apex is closer to what you're asking about, it is just a series of statements and can have methods defined as top-level members without defining a containing class. When executed it runs like a normal procedural execution.

Because Anonymous Apex has such a different structure I haven't build the form of the pieces yet. It doesn't have any unique structures, simply a different top-level structure (or the absence of it).

Mostly I haven't decided if I want the general parser to guess that something is Anonymous Apex or if I want to limit it to a different file extension `.apex` as is often done (though not always) and better tune the syntax affordances to that context only instead of trying to mix and match and end up with loser parsing overall.

**Comment by mjambon** [comment]
That's super useful, thank you. For Semgrep, ideally, we use a [single grammar that allows various entry points](https://github.com/returntocorp/ocaml-tree-sitter-semgrep/blob/main/lang/semgrep-grammars/src/semgrep-sfapex/apex/grammar.js) because Semgrep patterns typically allow simpler constructs than top-level constructs of the target language. If some target piece of code is a simple expression but the context only allows class definitions, we'd inspect the AST after parsing and raise an error.
